### ISSUE TITLE
Need for help when running val. Is there any file lost or need created by myself?

### ISSUE THREAD

**Issue by leonmakise** [tegusi/EAGRNet#3]
When I did what you ask, and training 1 epoch, I encounter an error for val.
Traceback (most recent call last):
  File "train.py", line 322, in <module>
    main()
  File "train.py", line 307, in main
    mIoU, f1 = compute_mean_ioU(parsing_preds, scales, centers, args.num_classes, args.data_dir, input_size, 'test', True)
  File "/data/users/majiaqi/EAGRNet/utils/miou.py", line 104, in compute_mean_ioU
    proj = np.load(os.path.join(datadir, 'project', im_name + '.npy'))
  File "/data/users/majiaqi/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 428, in load
    fid = open(os_fspath(file), "rb")
FileNotFoundError: [Errno 2] No such file or directory: './dataset/Helen/project/1019068877_1.npy'

It seems that miou.py need some kind of .npy file for each image.
Can you provide some advice? Thanks a lot!

**Comment by wxqlab** [comment]
Hi, @leonmakise 

do you solve this problem, I got the same problem with you. But I don't have any idea for that.
